[package]
name = "i3"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.*", default-features = false, features = ["derive"] }
serde_json = { version = "1.*", default-features = false, features = ["std"] }

[lints]
workspace = true
