[package]
name = "i3"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.*", default-features = false, features = ["derive"] }
serde_json = { version = "1.*", default-features = false, features = ["std"] }

[lints]
workspace = true
